# Gavin lyons 06-2021
# Makefile to install library for ST7735_TFT_RPI.
# URL: https://github.com/gavinlyonsrepo/ST7735_TFT_RPI
# Library is installed to /usr/lib and include files are placed at /usr/include.

# == Options ==
# 1. make = compile library
# 2. make install = install library to filesystem (may need sudo)
# 3. make clean = deletes .o files generated by step 1 from build directory
# 4. make uninstall  = uninstalls library (may need sudo)
# =============

# Where you want it installed
PREFIX=/usr
# where to place the library
LIBDIR=$(PREFIX)/lib
# library name
LIB=libST7735_TFT_RPI
# shared library name
LIBNAME=$(LIB).so.1.0

MD=mkdir
SRC=src
OBJ=obj
SRCS = $(wildcard $(SRC)/*.cpp)
OBJS = $(patsubst $(SRC)%.cpp,  $(OBJ)/%.o, $(SRCS))

CC=g++
CFLAGS= -march=native -mtune=native -mcpu=native  -Iinclude/
LDFLAGS= -lbcm2835

# make
all: clean pre-build ST7735_TFT_RPI

pre-build:
	@echo
	@echo "*****************"
	@echo "[START!]"
	@echo
	@echo "[MAKE LIBRARY]"
	$(MD) -vp $(OBJ)


# Make the library
ST7735_TFT_RPI: $(OBJS)
	$(CC) -shared -Wl,-soname,$(LIB).so.1 $(CFLAGS) $(LDFLAGS)  -o ${LIBNAME} $^

# Library parts
$(OBJ)/%.o: $(SRC)/%.cpp
	$(CC) -Wall -fPIC -c $(CFLAGS) $< -o $@

# Install the library to LIBPATH
install:
	@echo
	@echo "*****************"
	@echo "[INSTALL LIBRARY]"
	@if ( test ! -d $(PREFIX)/lib ) ; then mkdir -vp $(PREFIX)/lib ; fi
	@install -vm 0755 ${LIBNAME} ${LIBDIR}
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so.1
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so
	@ldconfig
	@rm -rvf ${LIB}.*
	@echo "*****************"
	@echo
	@echo "[INSTALL HEADERS]"
	@if ( test ! -d $(PREFIX)/include ) ; then mkdir -p $(PREFIX)/include ; fi
	@cp -vf  include/ST7735_TFT* $(PREFIX)/include

	@echo "[DONE!]"

# Uninstall the library
uninstall:
	@echo "******************"
	@echo "[UNINSTALL LIBRARY]"
	@rm -vf ${LIBDIR}/${LIB}.*

	@echo "[UNINSTALL HEADERS]"
	@rm -rvf  $(PREFIX)/include/ST7735_TFT*
	@echo "[DONE!]"

# clear build files
clean:
	@echo "******************"
	@echo "[CLEAN OBJECT FILES]"
	rm -rvf $(OBJ)/*.o ${LIB}.*
	@echo "[DONE!]"
	@echo "******************"
